language: python
sudo: false
matrix:
  include:
  - name: Python 3.8
    dist: bionic
    python: 3.8
    node_js: 14
    env: GEN_DOC=yes

before_install:
  - pip3 install mkdocs-material
  - pip3 install --upgrade pip
  - pip3 install npm
  - pip3 install twine
  - pip3 install mkdocs-material
addons:
  apt:
    sources:
      - sourceline: 'deb http://be.archive.ubuntu.com/ubuntu/ bionic main restricted'
    update: true

cache:
  pip: true

git:
  depth: 3
  quiet: true

script:
  - make dist

after_success:
  - ./.docs.sh

notifications:
  email:
    on_success: never

deploy:
  - provider: pypi
    user: comwes
    password: $PYPIPROD
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      branch: master
