site_name: 数据结构总结
extra_css:
      - stylesheets/extra.css
nav:
      - 00-绪论/00-绪论.md
      - 1.线性表:
              - 1.1线性表: 01-线性表/01.1线性表.md
              - 1.2线性表的顺序存储: 01-线性表/01.2线性表的顺序表示.md
              - 1.3线性表的链式存储: 01-线性表/01.3线性表的链式存储.md
              - 1.4双链表: 01-线性表/01.4双链表.md
              - 1.5循环链表: 01-线性表/01.5循环链表.md
              - 1.6静态链表: 01-线性表/01.6静态链表.md
      - 2.栈和队列:
              - 2.1栈: 02-栈和队列/2.1栈.md
              - 2.2顺序栈——栈的顺序存储: 02-栈和队列/2.2顺序栈——栈的顺序存储.md
              - 2.3链栈——栈的链式存储: 02-栈和队列/2.3链栈——栈的链式存储.md
              - 2.4栈的应用: 02-栈和队列/2.4栈的应用.md
              - 2.5队列: 02-栈和队列/3.1队列.md
              - 2.6队列的顺序存储: 02-栈和队列/3.2顺序队列(循环队列)——队列的顺序存储.md
              - 2.7队列的链式存储: 02-栈和队列/3.3链队列——队列的链式存储.md
              - 2.8双端队列: 02-栈和队列/3.4双端队列——队列的改进.md
              - 2.9队列的应用: 02-栈和队列/3.5队列的应用.md
              - 2.10特殊矩阵的压缩存储: 02-栈和队列/3.6特殊矩阵的压缩存储.md
      - 3.串:
              - 3.1串: 03-串/4.1串.md
              - 3.2串的存储结构: 03-串/4.2串的存储结构.md
              - 3.3字符串模式匹配: 03-串/4.3字符串模式匹配.md
      - 4.树:
              - 4.1树: 04-树/5.1树.md
              - 4.2二叉树: 04-树/5.2二叉树.md
              - 4.3线索二叉树: 04-树/5.3线索二叉树.md
              - 4.4树的存储结构: 04-树/5.4树的存储结构.md
              - 4.5二叉排序树: 04-树/5.5二叉排序树.md
              - 4.6平衡二叉树: 04-树/5.6平衡二叉树.md
              - 4.7哈夫曼树: 04-树/5.7哈夫曼树.md
      - 5.图:
              - 5.1图: 05-图/6.1图.md
              - 5.2图的存储结构: 05-图/6.2图的存储结构.md
              - 5.3图的基本操作: 05-图/6.3图的基本操作.md
              - 5.4图的遍历(BFS、DFS): 05-图/6.4图的遍历(BFS、DFS).md
              - 5.5最小生成树(Prim算法、Kruskal算法): 05-图/6.5最小生成树(Prim算法、Kruskal算法).md
              - 5.6最短路径(BFS、Dijkstra算法、Floyd算法): 05-图/6.6最短路径(BFS、Dijkstra算法、Floyd算法).md
              - 5.7有向无环图: 05-图/6.7有向无环图.md
              - 5.8拓扑排序: 05-图/6.8拓扑排序.md
              - 5.9关键路径: 05-图/6.9关键路径.md
      - 6.查找:
              - 6.1查找: 06-查找/7.1查找.md
              - 6.2顺序查找: 06-查找/7.2顺序查找.md
              - 6.3折半查找: 06-查找/7.3折半查找.md
              - 6.4分块查找: 06-查找/7.4分块查找.md
              - 6.5B树: 06-查找/7.5B树.md
              - 6.6B+树: 06-查找/7.6B+树.md
              - 6.7散列查找(哈希查找): 06-查找/7.7散列查找(哈希查找).md
      - 7.排序:
              - 7.1排序: 07-排序/8.1排序.md
              - 7.2插入排序（稳定）: 07-排序/8.2插入排序（稳定）.md
              - 7.3希尔排序（不稳定）: 07-排序/8.3希尔排序（不稳定）.md
              - 7.4冒泡排序（稳定）: 07-排序/8.4冒泡排序（稳定）.md
              - 7.5快速排序（不稳定）: 07-排序/8.5快速排序（不稳定）.md
              - 7.6简单选择排序（稳定）: 07-排序/8.6简单选择排序（稳定）.md
              - 7.7堆排序（不稳定）: 07-排序/8.7堆排序（不稳定）.md
              - 7.8归并排序（稳定）: 07-排序/8.8归并排序（稳定）.md
              - 7.9基数排序（稳定）: 07-排序/8.9基数排序（稳定）.md

theme:
      name: material
      features:
            - navigation.indexes
            - navigation.top
            - header.shadow
            - content.code.annotate
      language: zh
      palette:
            primary: blue
markdown_extensions:
      - admonition
      - pymdownx.arithmatex:
            generic: true
      - pymdownx.highlight:
              anchor_linenums: true
      - pymdownx.inlinehilite
      - pymdownx.snippets
      - pymdownx.details
      - pymdownx.superfences
      - pymdownx.tabbed
      - def_list
      - attr_list
      - toc:
            permalink: true
extra_javascript:
      - javascripts/mathjax.js
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# plugins:
#     - search
#     - mkpdfs:
#           design: docs/stylesheets/report.css
#           toc_title: 目录
#           company: 数据结构
