site_name: 数据结构总结
extra_css:
- stylesheets/extra.css
nav:
  - 1.线性表:
      - 1.1线性表: 1.1线性表.md
      - 1.2顺序表——线性表的顺序存储: 1.2顺序表——线性表的顺序存储.md
      - 1.3单链表——线性表的链式存储: 1.3单链表——线性表的链式存储.md
      - 1.4双链表——单链表的改进: 1.4双链表——单链表的改进.md
      - 1.5循环链表——单双链表的改进: 1.5循环链表——单双链表的改进.md
      - 1.6静态链表: 1.6静态链表.md
  - 2.栈:
      - 2.1栈: 2.1栈.md
      - 2.2顺序栈——栈的顺序存储: 2.2顺序栈——栈的顺序存储.md
      - 2.3链栈——栈的链式存储: 2.3链栈——栈的链式存储.md
      - 2.4栈的应用: 2.4栈的应用.md
  - 3.队列:
      - 3.1队列: 3.1队列.md
      - 3.2顺序队列(循环队列)——队列的顺序存储: 3.2顺序队列(循环队列)——队列的顺序存储.md
      - 3.3链队列——队列的链式存储: 3.3链队列——队列的链式存储.md
      - 3.4双端队列——队列的改进: 3.4双端队列——队列的改进.md
      - 3.5队列的应用: 3.5队列的应用.md
      - 3.6特殊矩阵的压缩存储: 3.6特殊矩阵的压缩存储.md
  - 4.串:
      - 4.1串: 4.1串.md
      - 4.2串的存储结构: 4.2串的存储结构.md
      - 4.3字符串模式匹配: 4.3字符串模式匹配.md
  - 5.树:
      - 5.1树: 5.1树.md
      - 5.2二叉树: 5.2二叉树.md
      - 5.3线索二叉树: 5.3线索二叉树.md
      - 5.4树的存储结构: 5.4树的存储结构.md
      - 5.5二叉排序树: 5.5二叉排序树.md
      - 5.6平衡二叉树: 5.6平衡二叉树.md
      - 5.7哈夫曼树: 5.7哈夫曼树.md
  - 6.图:
      - 6.1图: 6.1图.md
      - 6.2图的存储结构: 6.2图的存储结构.md
      - 6.3图的基本操作: 6.3图的基本操作.md
      - 6.4图的遍历(BFS、DFS): 6.4图的遍历(BFS、DFS).md
      - 6.5最小生成树(Prim算法、Kruskal算法): 6.5最小生成树(Prim算法、Kruskal算法).md
      - 6.6最短路径(BFS、Dijkstra算法、Floyd算法): 6.6最短路径(BFS、Dijkstra算法、Floyd算法).md
      - 6.7有向无环图: 6.7有向无环图.md
      - 6.8拓扑排序: 6.8拓扑排序.md
      - 6.9关键路径: 6.9关键路径.md
  - 7.查找:
      - 7.1查找: 7.1查找.md
      - 7.2顺序查找: 7.2顺序查找.md
      - 7.3折半查找: 7.3折半查找.md
      - 7.4分块查找: 7.4分块查找.md
      - 7.5B树: 7.5B树.md
      - 7.6B+树: 7.6B+树.md
      - 7.7散列查找(哈希查找): 7.7散列查找(哈希查找).md
  - 8.排序:
      - 8.1排序: 8.1排序.md
      - 8.2插入排序（稳定）: 8.2插入排序（稳定）.md
      - 8.3希尔排序（不稳定）: 8.3希尔排序（不稳定）.md
      - 8.4冒泡排序（稳定）: 8.4冒泡排序（稳定）.md
      - 8.5快速排序（不稳定）: 8.5快速排序（不稳定）.md
      - 8.6简单选择排序（稳定）: 8.6简单选择排序（稳定）.md
      - 8.7堆排序（不稳定）: 8.7堆排序（不稳定）.md
      - 8.8归并排序（稳定）: 8.8归并排序（稳定）.md
      - 8.9基数排序（稳定）: 8.9基数排序（稳定）.md

theme: readthedocs
theme:
  name: material
  features:
  - navigation.indexes
  - navigation.top
  - header.shadow
  - content.code.annotate
  font:
    text: Oswald
    code: Roboto Mono
  language: zh
  palette:
    primary: blue
markdown_extensions:
- admonition
- pymdownx.arithmatex
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed
- def_list
- attr_list
- toc:
    permalink: true
# plugins:
# - search
# - mkpdfs:
#    design: docs/stylesheets/report.css
#    toc_title: 目录
#    company: 数据结构